spring.application.name=sensor-intelligence-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/sensor_intelligence
spring.datasource.username=adityarajsingh
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true